spring:
  application:
    name: spring_actuator_prometheus_grafana
  datasource:
    url: jdbc:h2:file:./data/testdb;AUTO_SERVER=true
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
server:
  port: 7001
